<?php

namespace Wuyu\World\Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        DB::table('countries')->insert([
            ['name' => 'Andorra', 'abbreviation' => 'AD', 'zh_name' => '安道尔共和国', 'continent_code' => 'EU', 'phone_code' => '376', 'currency' => 'USD'],
            ['name' => 'United Arab Emirates', 'abbreviation' => 'AE', 'zh_name' => '阿拉伯联合酋长国', 'continent_code' => 'AS', 'phone_code' => '971', 'currency' => 'AED'],
            ['name' => 'Afghanistan', 'abbreviation' => 'AF', 'zh_name' => '阿富汗', 'continent_code' => 'AS', 'phone_code' => '93', 'currency' => 'AFA'],
            ['name' => 'Antigua and Barbuda', 'abbreviation' => 'AG', 'zh_name' => '安提瓜和巴布达', 'continent_code' => 'NA', 'phone_code' => '1268', 'currency' => 'XCD'],
            ['name' => 'Anguilla', 'abbreviation' => 'AI', 'zh_name' => '安圭拉', 'continent_code' => 'NA', 'phone_code' => '1264', 'currency' => 'XCD'],
            ['name' => 'Albania', 'abbreviation' => 'AL', 'zh_name' => '阿尔巴尼亚', 'continent_code' => 'EU', 'phone_code' => '355', 'currency' => 'ALL'],
            ['name' => 'Armenia', 'abbreviation' => 'AM', 'zh_name' => '亚美尼亚', 'continent_code' => 'AS', 'phone_code' => '374', 'currency' => 'AMD'],
            ['name' => 'Ascension', 'abbreviation' => 'AC', 'zh_name' => '阿森松', 'continent_code' => 'AF', 'phone_code' => '247', 'currency' => 'SHP'],
            ['name' => 'Angola', 'abbreviation' => 'AO', 'zh_name' => '安哥拉', 'continent_code' => 'AS', 'phone_code' => '244', 'currency' => 'AOA'],
            ['name' => 'Argentina', 'abbreviation' => 'AR', 'zh_name' => '阿根廷', 'continent_code' => 'SA', 'phone_code' => '54', 'currency' => 'ARS'],
            ['name' => 'Austria', 'abbreviation' => 'AT', 'zh_name' => '奥地利', 'continent_code' => 'EU', 'phone_code' => '43', 'currency' => 'EUR'],
            ['name' => 'Australia', 'abbreviation' => 'AU', 'zh_name' => '澳大利亚', 'continent_code' => 'OC', 'phone_code' => '61', 'currency' => 'AUD'],
            ['name' => 'Azerbaijan', 'abbreviation' => 'AZ', 'zh_name' => '阿塞拜疆', 'continent_code' => 'AS', 'phone_code' => '994', 'currency' => 'AZN'],
            ['name' => 'Barbados', 'abbreviation' => 'BB', 'zh_name' => '巴巴多斯', 'continent_code' => 'NA', 'phone_code' => '1246', 'currency' => 'BBD'],
            ['name' => 'Bangladesh', 'abbreviation' => 'BD', 'zh_name' => '孟加拉国', 'continent_code' => 'AS', 'phone_code' => '880', 'currency' => 'BDT'],
            ['name' => 'Belgium', 'abbreviation' => 'BE', 'zh_name' => '比利时', 'continent_code' => 'EU', 'phone_code' => '32', 'currency' => 'EUR'],
            ['name' => 'Burkina-faso', 'abbreviation' => 'BF', 'zh_name' => '布基纳法索', 'continent_code' => 'AF', 'phone_code' => '226', 'currency' => 'XOF'],
            ['name' => 'Bulgaria', 'abbreviation' => 'BG', 'zh_name' => '保加利亚', 'continent_code' => 'EU', 'phone_code' => '359', 'currency' => 'BGN'],
            ['name' => 'Bahrain', 'abbreviation' => 'BH', 'zh_name' => '巴林', 'continent_code' => 'AS', 'phone_code' => '973', 'currency' => 'BHD'],
            ['name' => 'Burundi', 'abbreviation' => 'BI', 'zh_name' => '布隆迪', 'continent_code' => 'AF', 'phone_code' => '257', 'currency' => 'BIF'],
            ['name' => 'Benin', 'abbreviation' => 'BJ', 'zh_name' => '贝宁', 'continent_code' => 'AF', 'phone_code' => '229', 'currency' => 'XOF'],
            ['name' => 'Palestine', 'abbreviation' => 'BL', 'zh_name' => '巴勒斯坦', 'continent_code' => 'AS', 'phone_code' => '970', 'currency' => 'ILS'],
            ['name' => 'Bermuda', 'abbreviation' => 'BM', 'zh_name' => '百慕大群岛', 'continent_code' => 'NA', 'phone_code' => '1441', 'currency' => 'BMD'],
            ['name' => 'Brunei', 'abbreviation' => 'BN', 'zh_name' => '文莱', 'continent_code' => 'AS', 'phone_code' => '673', 'currency' => 'BND'],
            ['name' => 'Bolivia', 'abbreviation' => 'BO', 'zh_name' => '玻利维亚', 'continent_code' => 'SA', 'phone_code' => '591', 'currency' => 'BOB'],
            ['name' => 'Brazil', 'abbreviation' => 'BR', 'zh_name' => '巴西', 'continent_code' => 'SA', 'phone_code' => '55', 'currency' => 'BRL'],
            ['name' => 'Bahamas', 'abbreviation' => 'BS', 'zh_name' => '巴哈马', 'continent_code' => 'NA', 'phone_code' => '1242', 'currency' => 'BSD'],
            ['name' => 'Botswana', 'abbreviation' => 'BW', 'zh_name' => '博茨瓦纳', 'continent_code' => 'AF', 'phone_code' => '267', 'currency' => 'BWP'],
            ['name' => 'Belarus', 'abbreviation' => 'BY', 'zh_name' => '白俄罗斯', 'continent_code' => 'EU', 'phone_code' => '375', 'currency' => 'BYR'],
            ['name' => 'Belize', 'abbreviation' => 'BZ', 'zh_name' => '伯利兹', 'continent_code' => 'NA', 'phone_code' => '501', 'currency' => 'BZD'],
            ['name' => 'Canada', 'abbreviation' => 'CA', 'zh_name' => '加拿大', 'continent_code' => 'NA', 'phone_code' => '1', 'currency' => 'CAD'],
            ['name' => 'Cayman Is.', 'abbreviation' => 'KY', 'zh_name' => '开曼群岛', 'continent_code' => 'NA', 'phone_code' => '1345', 'currency' => 'KYD'],
            ['name' => 'Central African Republic', 'abbreviation' => 'CF', 'zh_name' => '中非共和国', 'continent_code' => 'AF', 'phone_code' => '236', 'currency' => 'XAF'],
            ['name' => 'Congo', 'abbreviation' => 'CG', 'zh_name' => '刚果', 'continent_code' => 'AF', 'phone_code' => '242', 'currency' => 'CDF'],
            ['name' => 'Switzerland', 'abbreviation' => 'CH', 'zh_name' => '瑞士', 'continent_code' => 'EU', 'phone_code' => '41', 'currency' => 'CHF'],
            ['name' => 'Cook Is.', 'abbreviation' => 'CK', 'zh_name' => '库克群岛', 'continent_code' => 'OC', 'phone_code' => '682', 'currency' => 'NZD'],
            ['name' => 'Chile', 'abbreviation' => 'CL', 'zh_name' => '智利', 'continent_code' => 'SA', 'phone_code' => '56', 'currency' => 'CLP'],
            ['name' => 'Cameroon', 'abbreviation' => 'CM', 'zh_name' => '喀麦隆', 'continent_code' => 'AF', 'phone_code' => '237', 'currency' => 'XAF'],
            ['name' => 'China', 'abbreviation' => 'CN', 'zh_name' => '中国', 'continent_code' => 'AS', 'phone_code' => '86', 'currency' => 'CNY'],
            ['name' => 'Colombia', 'abbreviation' => 'CO', 'zh_name' => '哥伦比亚', 'continent_code' => 'SA', 'phone_code' => '57', 'currency' => 'COP'],
            ['name' => 'Costa Rica', 'abbreviation' => 'CR', 'zh_name' => '哥斯达黎加', 'continent_code' => 'NA', 'phone_code' => '506', 'currency' => 'CRC'],
            ['name' => 'Cuba', 'abbreviation' => 'CU', 'zh_name' => '古巴', 'continent_code' => 'NA', 'phone_code' => '53', 'currency' => 'CUP'],
            ['name' => 'Cyprus', 'abbreviation' => 'CY', 'zh_name' => '塞浦路斯', 'continent_code' => 'EU', 'phone_code' => '357', 'currency' => 'EUR'],
            ['name' => 'Czech Republic', 'abbreviation' => 'CZ', 'zh_name' => '捷克', 'continent_code' => 'EU', 'phone_code' => '420', 'currency' => 'CZK'],
            ['name' => 'Germany', 'abbreviation' => 'DE', 'zh_name' => '德国', 'continent_code' => 'EU', 'phone_code' => '49', 'currency' => 'EUR'],
            ['name' => 'Djibouti', 'abbreviation' => 'DJ', 'zh_name' => '吉布提', 'continent_code' => 'AF', 'phone_code' => '253', 'currency' => 'DJF'],
            ['name' => 'Denmark', 'abbreviation' => 'DK', 'zh_name' => '丹麦', 'continent_code' => 'EU', 'phone_code' => '45', 'currency' => 'DKK'],
            ['name' => 'Dominica Rep', 'abbreviation' => 'DO', 'zh_name' => '多米尼加共和国', 'continent_code' => 'NA', 'phone_code' => '1890', 'currency' => 'DOP'],
            ['name' => 'Algeria', 'abbreviation' => 'DZ', 'zh_name' => '阿尔及利亚', 'continent_code' => 'AF', 'phone_code' => '213', 'currency' => 'DZD'],
            ['name' => 'Ecuador', 'abbreviation' => 'EC', 'zh_name' => '厄瓜多尔', 'continent_code' => 'SA', 'phone_code' => '593', 'currency' => 'USD'],
            ['name' => 'Estonia', 'abbreviation' => 'EE', 'zh_name' => '爱沙尼亚', 'continent_code' => 'EU', 'phone_code' => '372', 'currency' => 'EUR'],
            ['name' => 'Egypt', 'abbreviation' => 'EG', 'zh_name' => '埃及', 'continent_code' => 'AF', 'phone_code' => '20', 'currency' => 'EGP'],
            ['name' => 'Spain', 'abbreviation' => 'ES', 'zh_name' => '西班牙', 'continent_code' => 'EU', 'phone_code' => '34', 'currency' => 'EUR'],
            ['name' => 'Ethiopia', 'abbreviation' => 'ET', 'zh_name' => '埃塞俄比亚', 'continent_code' => 'AF', 'phone_code' => '251', 'currency' => 'ETB'],
            ['name' => 'Finland', 'abbreviation' => 'FI', 'zh_name' => '芬兰', 'continent_code' => 'EU', 'phone_code' => '358', 'currency' => 'EUR'],
            ['name' => 'Fiji', 'abbreviation' => 'FJ', 'zh_name' => '斐济', 'continent_code' => 'OC', 'phone_code' => '679', 'currency' => 'FJD'],
            ['name' => 'France', 'abbreviation' => 'FR', 'zh_name' => '法国', 'continent_code' => 'EU', 'phone_code' => '33', 'currency' => 'EUR'],
            ['name' => 'Gabon', 'abbreviation' => 'GA', 'zh_name' => '加蓬', 'continent_code' => 'AF', 'phone_code' => '241', 'currency' => 'XAF'],
            ['name' => 'United Kiongdom', 'abbreviation' => 'GB', 'zh_name' => '英国', 'continent_code' => 'EU', 'phone_code' => '44', 'currency' => 'GBP'],
            ['name' => 'Grenada', 'abbreviation' => 'GD', 'zh_name' => '格林纳达', 'continent_code' => 'NA', 'phone_code' => '1809', 'currency' => 'XCD'],
            ['name' => 'Georgia', 'abbreviation' => 'GE', 'zh_name' => '格鲁吉亚', 'continent_code' => 'EU', 'phone_code' => '995', 'currency' => 'GEL'],
            ['name' => 'French Guiana', 'abbreviation' => 'GF', 'zh_name' => '法属圭亚那', 'continent_code' => 'SA', 'phone_code' => '594', 'currency' => 'EUR'],
            ['name' => 'Ghana', 'abbreviation' => 'GH', 'zh_name' => '加纳', 'continent_code' => 'AF', 'phone_code' => '233', 'currency' => 'GHS'],
            ['name' => 'Gibraltar', 'abbreviation' => 'GI', 'zh_name' => '直布罗陀', 'continent_code' => 'EU', 'phone_code' => '350', 'currency' => 'GIP'],
            ['name' => 'Gambia', 'abbreviation' => 'GM', 'zh_name' => '冈比亚', 'continent_code' => 'AF', 'phone_code' => '220', 'currency' => 'GMD'],
            ['name' => 'Guinea', 'abbreviation' => 'GN', 'zh_name' => '几内亚', 'continent_code' => 'AF', 'phone_code' => '224', 'currency' => 'GNF'],
            ['name' => 'Greece', 'abbreviation' => 'GR', 'zh_name' => '希腊', 'continent_code' => 'EU', 'phone_code' => '30', 'currency' => 'EUR'],
            ['name' => 'Guatemala', 'abbreviation' => 'GT', 'zh_name' => '危地马拉', 'continent_code' => 'NA', 'phone_code' => '502', 'currency' => 'GTQ'],
            ['name' => 'Guam', 'abbreviation' => 'GU', 'zh_name' => '关岛', 'continent_code' => 'OC', 'phone_code' => '1671', 'currency' => 'USD'],
            ['name' => 'Guyana', 'abbreviation' => 'GY', 'zh_name' => '圭亚那', 'continent_code' => 'SA', 'phone_code' => '592', 'currency' => 'GYD'],
            ['name' => 'Hongkong', 'abbreviation' => 'HK', 'zh_name' => '香港特别行政区', 'continent_code' => 'AS', 'phone_code' => '852', 'currency' => 'HKD'],
            ['name' => 'Honduras', 'abbreviation' => 'HN', 'zh_name' => '洪都拉斯', 'continent_code' => 'NA', 'phone_code' => '504', 'currency' => 'HNL'],
            ['name' => 'Haiti', 'abbreviation' => 'HT', 'zh_name' => '海地', 'continent_code' => 'NA', 'phone_code' => '509', 'currency' => 'HTG'],
            ['name' => 'Hungary', 'abbreviation' => 'HU', 'zh_name' => '匈牙利', 'continent_code' => 'EU', 'phone_code' => '36', 'currency' => 'HUF'],
            ['name' => 'Indonesia', 'abbreviation' => 'ID', 'zh_name' => '印度尼西亚', 'continent_code' => 'AS', 'phone_code' => '62', 'currency' => 'IDR'],
            ['name' => 'Ireland', 'abbreviation' => 'IE', 'zh_name' => '爱尔兰', 'continent_code' => 'EU', 'phone_code' => '353', 'currency' => 'EUR'],
            ['name' => 'Israel', 'abbreviation' => 'IL', 'zh_name' => '以色列', 'continent_code' => 'AS', 'phone_code' => '972', 'currency' => 'ILS'],
            ['name' => 'India', 'abbreviation' => 'IN', 'zh_name' => '印度', 'continent_code' => 'AS', 'phone_code' => '91', 'currency' => 'INR'],
            ['name' => 'Iraq', 'abbreviation' => 'IQ', 'zh_name' => '伊拉克', 'continent_code' => 'AS', 'phone_code' => '964', 'currency' => 'IQD'],
            ['name' => 'Iran', 'abbreviation' => 'IR', 'zh_name' => '伊朗', 'continent_code' => 'AS', 'phone_code' => '98', 'currency' => 'IRR'],
            ['name' => 'Iceland', 'abbreviation' => 'IS', 'zh_name' => '冰岛', 'continent_code' => 'EU', 'phone_code' => '354', 'currency' => 'ISK'],
            ['name' => 'Italy', 'abbreviation' => 'IT', 'zh_name' => '意大利', 'continent_code' => 'EU', 'phone_code' => '39', 'currency' => 'EUR'],
            ['name' => 'Ivory Coast', 'abbreviation' => 'CI', 'zh_name' => '科特迪瓦', 'continent_code' => 'AS', 'phone_code' => '225', 'currency' => 'XOF'],
            ['name' => 'Jamaica', 'abbreviation' => 'JM', 'zh_name' => '牙买加', 'continent_code' => 'NA', 'phone_code' => '1876', 'currency' => 'JMD'],
            ['name' => 'Jordan', 'abbreviation' => 'JO', 'zh_name' => '约旦', 'continent_code' => 'AS', 'phone_code' => '962', 'currency' => 'JOD'],
            ['name' => 'Japan', 'abbreviation' => 'JP', 'zh_name' => '日本', 'continent_code' => 'AS', 'phone_code' => '81', 'currency' => 'JPY'],
            ['name' => 'Kenya', 'abbreviation' => 'KE', 'zh_name' => '肯尼亚', 'continent_code' => 'AF', 'phone_code' => '254', 'currency' => 'KES'],
            ['name' => 'Kyrgyzstan', 'abbreviation' => 'KG', 'zh_name' => '吉尔吉斯坦', 'continent_code' => 'AS', 'phone_code' => '331', 'currency' => 'KGS'],
            ['name' => 'Kampuchea (Cambodia )', 'abbreviation' => 'KH', 'zh_name' => '柬埔寨', 'continent_code' => 'AS', 'phone_code' => '855', 'currency' => 'KHR'],
            ['name' => 'North Korea', 'abbreviation' => 'KP', 'zh_name' => '朝鲜', 'continent_code' => 'AS', 'phone_code' => '850', 'currency' => 'KPW'],
            ['name' => 'Korea', 'abbreviation' => 'KR', 'zh_name' => '韩国', 'continent_code' => 'AS', 'phone_code' => '82', 'currency' => 'KRW'],
            ['name' => 'Republic of Ivory Coast', 'abbreviation' => 'KT', 'zh_name' => '科特迪瓦共和国', 'continent_code' => 'AF', 'phone_code' => '225', 'currency' => 'XOF'],
            ['name' => 'Kuwait', 'abbreviation' => 'KW', 'zh_name' => '科威特', 'continent_code' => 'AS', 'phone_code' => '965', 'currency' => 'KWD'],
            ['name' => 'Kazakstan', 'abbreviation' => 'KZ', 'zh_name' => '哈萨克斯坦', 'continent_code' => 'EU', 'phone_code' => '327', 'currency' => 'KZT'],
            ['name' => 'Laos', 'abbreviation' => 'LA', 'zh_name' => '老挝', 'continent_code' => 'AS', 'phone_code' => '856', 'currency' => 'LAK'],
            ['name' => 'Lebanon', 'abbreviation' => 'LB', 'zh_name' => '黎巴嫩', 'continent_code' => 'AS', 'phone_code' => '961', 'currency' => 'LBP'],
            ['name' => 'St.Lucia', 'abbreviation' => 'LC', 'zh_name' => '圣卢西亚', 'continent_code' => 'NA', 'phone_code' => '1758', 'currency' => 'XCD'],
            ['name' => 'Liechtenstein', 'abbreviation' => 'LI', 'zh_name' => '列支敦士登', 'continent_code' => 'EU', 'phone_code' => '423', 'currency' => '‎CHF'],
            ['name' => 'Sri Lanka', 'abbreviation' => 'LK', 'zh_name' => '斯里兰卡', 'continent_code' => 'AS', 'phone_code' => '94', 'currency' => 'LKR'],
            ['name' => 'Liberia', 'abbreviation' => 'LR', 'zh_name' => '利比里亚', 'continent_code' => 'AF', 'phone_code' => '231', 'currency' => 'LRD'],
            ['name' => 'Lesotho', 'abbreviation' => 'LS', 'zh_name' => '莱索托', 'continent_code' => 'AF', 'phone_code' => '266', 'currency' => 'ZAR'],
            ['name' => 'Lithuania', 'abbreviation' => 'LT', 'zh_name' => '立陶宛', 'continent_code' => 'EU', 'phone_code' => '370', 'currency' => 'EUR'],
            ['name' => 'Luxembourg', 'abbreviation' => 'LU', 'zh_name' => '卢森堡', 'continent_code' => 'EU', 'phone_code' => '352', 'currency' => 'EUR'],
            ['name' => 'Latvia', 'abbreviation' => 'LV', 'zh_name' => '拉脱维亚', 'continent_code' => 'EU', 'phone_code' => '371', 'currency' => 'EUR'],
            ['name' => 'Libya', 'abbreviation' => 'LY', 'zh_name' => '利比亚', 'continent_code' => 'AF', 'phone_code' => '218', 'currency' => 'LYD'],
            ['name' => 'Morocco', 'abbreviation' => 'MA', 'zh_name' => '摩洛哥', 'continent_code' => 'AF', 'phone_code' => '212', 'currency' => 'MAD'],
            ['name' => 'Monaco', 'abbreviation' => 'MC', 'zh_name' => '摩纳哥', 'continent_code' => 'EU', 'phone_code' => '377', 'currency' => 'EUR'],
            ['name' => 'Moldova, Republic of', 'abbreviation' => 'MD', 'zh_name' => '摩尔多瓦', 'continent_code' => 'EU', 'phone_code' => '373', 'currency' => 'MDL'],
            ['name' => 'Madagascar', 'abbreviation' => 'MG', 'zh_name' => '马达加斯加', 'continent_code' => 'AF', 'phone_code' => '261', 'currency' => 'MGA'],
            ['name' => 'Mali', 'abbreviation' => 'ML', 'zh_name' => '马里', 'continent_code' => 'AF', 'phone_code' => '223', 'currency' => 'XOF'],
            ['name' => 'Burma', 'abbreviation' => 'MM', 'zh_name' => '缅甸', 'continent_code' => 'AS', 'phone_code' => '95', 'currency' => 'MMK'],
            ['name' => 'Mongolia', 'abbreviation' => 'MN', 'zh_name' => '蒙古', 'continent_code' => 'AS', 'phone_code' => '976', 'currency' => 'MNT'],
            ['name' => 'Macao', 'abbreviation' => 'MO', 'zh_name' => '澳门', 'continent_code' => 'AS', 'phone_code' => '853', 'currency' => 'MOP'],
            ['name' => 'Montserrat Is', 'abbreviation' => 'MS', 'zh_name' => '蒙特塞拉特岛', 'continent_code' => 'NA', 'phone_code' => '1664', 'currency' => 'XCD'],
            ['name' => 'Malta', 'abbreviation' => 'MT', 'zh_name' => '马耳他', 'continent_code' => 'EU', 'phone_code' => '356', 'currency' => 'EUR'],
            ['name' => 'Mariana Is', 'abbreviation' => 'MP', 'zh_name' => '马里亚那群岛', 'continent_code' => 'OC', 'phone_code' => '1670', 'currency' => 'USD'],
            ['name' => 'Martinique', 'abbreviation' => 'MQ', 'zh_name' => '马提尼克', 'continent_code' => 'NA', 'phone_code' => '596', 'currency' => 'EUR'],
            ['name' => 'Mauritius', 'abbreviation' => 'MU', 'zh_name' => '毛里求斯', 'continent_code' => 'AF', 'phone_code' => '230', 'currency' => 'MUR'],
            ['name' => 'Maldives', 'abbreviation' => 'MV', 'zh_name' => '马尔代夫', 'continent_code' => 'AS', 'phone_code' => '960', 'currency' => 'MVR'],
            ['name' => 'Malawi', 'abbreviation' => 'MW', 'zh_name' => '马拉维', 'continent_code' => 'AF', 'phone_code' => '265', 'currency' => 'MWK'],
            ['name' => 'Mexico', 'abbreviation' => 'MX', 'zh_name' => '墨西哥', 'continent_code' => 'NA', 'phone_code' => '52', 'currency' => 'MXN'],
            ['name' => 'Malaysia', 'abbreviation' => 'MY', 'zh_name' => '马来西亚', 'continent_code' => 'AS', 'phone_code' => '60', 'currency' => 'MYR'],
            ['name' => 'Mozambique', 'abbreviation' => 'MZ', 'zh_name' => '莫桑比克', 'continent_code' => 'AF', 'phone_code' => '258', 'currency' => 'MZN'],
            ['name' => 'Namibia', 'abbreviation' => 'NA', 'zh_name' => '纳米比亚', 'continent_code' => 'AF', 'phone_code' => '264', 'currency' => 'NAD'],
            ['name' => 'Niger', 'abbreviation' => 'NE', 'zh_name' => '尼日尔', 'continent_code' => 'AF', 'phone_code' => '977', 'currency' => 'XOF'],
            ['name' => 'Nigeria', 'abbreviation' => 'NG', 'zh_name' => '尼日利亚', 'continent_code' => 'AF', 'phone_code' => '234', 'currency' => 'NGN'],
            ['name' => 'Nicaragua', 'abbreviation' => 'NI', 'zh_name' => '尼加拉瓜', 'continent_code' => 'NA', 'phone_code' => '505', 'currency' => 'NIO'],
            ['name' => 'Netherlands', 'abbreviation' => 'NL', 'zh_name' => '荷兰', 'continent_code' => 'EU', 'phone_code' => '31', 'currency' => 'EUR'],
            ['name' => 'Norway', 'abbreviation' => 'NO', 'zh_name' => '挪威', 'continent_code' => 'EU', 'phone_code' => '47', 'currency' => '挪威'],
            ['name' => 'Nepal', 'abbreviation' => 'NP', 'zh_name' => '尼泊尔', 'continent_code' => 'AS', 'phone_code' => '977', 'currency' => 'NPR'],
            ['name' => 'Netheriands Antilles', 'abbreviation' => 'AN', 'zh_name' => '荷属安的列斯', 'continent_code' => 'NA', 'phone_code' => '599', 'currency' => 'ANG'],
            ['name' => 'Nauru', 'abbreviation' => 'NR', 'zh_name' => '瑙鲁', 'continent_code' => 'OC', 'phone_code' => '674', 'currency' => 'AUD'],
            ['name' => 'New Zealand', 'abbreviation' => 'NZ', 'zh_name' => '新西兰', 'continent_code' => 'OC', 'phone_code' => '64', 'currency' => 'NZD'],
            ['name' => 'Oman', 'abbreviation' => 'OM', 'zh_name' => '阿曼', 'continent_code' => 'AS', 'phone_code' => '968', 'currency' => 'OMR'],
            ['name' => 'Panama', 'abbreviation' => 'PA', 'zh_name' => '巴拿马', 'continent_code' => 'NA', 'phone_code' => '507', 'currency' => 'PAB'],
            ['name' => 'Peru', 'abbreviation' => 'PE', 'zh_name' => '秘鲁', 'continent_code' => 'SA', 'phone_code' => '51', 'currency' => 'PEN'],
            ['name' => 'French Polynesia', 'abbreviation' => 'PF', 'zh_name' => '法属玻利尼西亚', 'continent_code' => 'OC', 'phone_code' => '689', 'currency' => 'XPF'],
            ['name' => 'Papua New Cuinea', 'abbreviation' => 'PG', 'zh_name' => '巴布亚新几内亚', 'continent_code' => 'OC', 'phone_code' => '675', 'currency' => 'PGK'],
            ['name' => 'Philippines', 'abbreviation' => 'PH', 'zh_name' => '菲律宾', 'continent_code' => 'AS', 'phone_code' => '63', 'currency' => 'PHP'],
            ['name' => 'Pakistan', 'abbreviation' => 'PK', 'zh_name' => '巴基斯坦', 'continent_code' => 'AS', 'phone_code' => '92', 'currency' => 'PKR'],
            ['name' => 'Poland', 'abbreviation' => 'PL', 'zh_name' => '波兰', 'continent_code' => 'EU', 'phone_code' => '48', 'currency' => 'PLN'],
            ['name' => 'Puerto Rico', 'abbreviation' => 'PR', 'zh_name' => '波多黎各', 'continent_code' => 'NA', 'phone_code' => '1787', 'currency' => 'USD'],
            ['name' => 'Portugal', 'abbreviation' => 'PT', 'zh_name' => '葡萄牙', 'continent_code' => 'EU', 'phone_code' => '351', 'currency' => 'EUR'],
            ['name' => 'Paraguay', 'abbreviation' => 'PY', 'zh_name' => '巴拉圭', 'continent_code' => 'SA', 'phone_code' => '595', 'currency' => 'PYG'],
            ['name' => 'Qatar', 'abbreviation' => 'QA', 'zh_name' => '卡塔尔', 'continent_code' => 'AS', 'phone_code' => '974', 'currency' => 'QAR'],
            ['name' => 'Reunion', 'abbreviation' => 'RE', 'zh_name' => '留尼旺', 'continent_code' => 'AF', 'phone_code' => '262', 'currency' => 'EUR'],
            ['name' => 'Romania', 'abbreviation' => 'RO', 'zh_name' => '罗马尼亚', 'continent_code' => 'EU', 'phone_code' => '40', 'currency' => 'RON'],
            ['name' => 'Russia', 'abbreviation' => 'RU', 'zh_name' => '俄罗斯', 'continent_code' => 'EU', 'phone_code' => '7', 'currency' => 'RUB'],
            ['name' => 'Saudi Arabia', 'abbreviation' => 'SA', 'zh_name' => '沙特阿拉伯', 'continent_code' => 'AS', 'phone_code' => '966', 'currency' => 'SAR'],
            ['name' => 'Solomon Is', 'abbreviation' => 'SB', 'zh_name' => '所罗门群岛', 'continent_code' => 'OC', 'phone_code' => '677', 'currency' => 'SBD'],
            ['name' => 'Seychelles', 'abbreviation' => 'SC', 'zh_name' => '塞舌尔', 'continent_code' => 'AF', 'phone_code' => '248', 'currency' => 'SCR'],
            ['name' => 'Sudan', 'abbreviation' => 'SD', 'zh_name' => '苏丹', 'continent_code' => 'AF', 'phone_code' => '249', 'currency' => 'SDG'],
            ['name' => 'Sweden', 'abbreviation' => 'SE', 'zh_name' => '瑞典', 'continent_code' => 'EU', 'phone_code' => '46', 'currency' => 'SEK'],
            ['name' => 'Singapore', 'abbreviation' => 'SG', 'zh_name' => '新加坡', 'continent_code' => 'AS', 'phone_code' => '65', 'currency' => 'SGD'],
            ['name' => 'Slovenia', 'abbreviation' => 'SI', 'zh_name' => '斯洛文尼亚', 'continent_code' => 'EU', 'phone_code' => '386', 'currency' => 'EUR'],
            ['name' => 'Slovakia', 'abbreviation' => 'SK', 'zh_name' => '斯洛伐克', 'continent_code' => 'EU', 'phone_code' => '421', 'currency' => 'EUR'],
            ['name' => 'Sierra Leone', 'abbreviation' => 'SL', 'zh_name' => '塞拉利昂', 'continent_code' => 'AF', 'phone_code' => '232', 'currency' => 'SLL'],
            ['name' => 'San Marino', 'abbreviation' => 'SM', 'zh_name' => '圣马力诺', 'continent_code' => 'EU', 'phone_code' => '378', 'currency' => 'EUR'],
            ['name' => 'American Samoa', 'abbreviation' => 'AS', 'zh_name' => '东萨摩亚(美)', 'continent_code' => 'OC', 'phone_code' => '684', 'currency' => 'USD'],
            ['name' => 'San Marino', 'abbreviation' => 'WS', 'zh_name' => '西萨摩亚', 'continent_code' => 'EU', 'phone_code' => '685', 'currency' => 'EUR'],
            ['name' => 'Senegal', 'abbreviation' => 'SN', 'zh_name' => '塞内加尔', 'continent_code' => 'AF', 'phone_code' => '221', 'currency' => 'XOF'],
            ['name' => 'Somali', 'abbreviation' => 'SO', 'zh_name' => '索马里', 'continent_code' => 'AF', 'phone_code' => '252', 'currency' => 'SOS'],
            ['name' => 'Suriname', 'abbreviation' => 'SR', 'zh_name' => '苏里南', 'continent_code' => 'SA', 'phone_code' => '597', 'currency' => 'SRD'],
            ['name' => 'Sao Tome and Principe', 'abbreviation' => 'ST', 'zh_name' => '圣多美和普林西比', 'continent_code' => 'AF', 'phone_code' => '239', 'currency' => 'STD'],
            ['name' => 'EI Salvador', 'abbreviation' => 'SV', 'zh_name' => '萨尔瓦多', 'continent_code' => 'NA', 'phone_code' => '503', 'currency' => 'SVC'],
            ['name' => 'Syria', 'abbreviation' => 'SY', 'zh_name' => '叙利亚', 'continent_code' => 'AS', 'phone_code' => '963', 'currency' => 'SYP'],
            ['name' => 'Swaziland', 'abbreviation' => 'SZ', 'zh_name' => '斯威士兰', 'continent_code' => 'AF', 'phone_code' => '268', 'currency' => 'SZL'],
            ['name' => 'Chad', 'abbreviation' => 'TD', 'zh_name' => '乍得', 'continent_code' => 'AF', 'phone_code' => '235', 'currency' => 'XAF'],
            ['name' => 'Togo', 'abbreviation' => 'TG', 'zh_name' => '多哥', 'continent_code' => 'AF', 'phone_code' => '228', 'currency' => 'XOF'],
            ['name' => 'Thailand', 'abbreviation' => 'TH', 'zh_name' => '泰国', 'continent_code' => 'AS', 'phone_code' => '66', 'currency' => 'THB'],
            ['name' => 'Tajikstan', 'abbreviation' => 'TJ', 'zh_name' => '塔吉克斯坦', 'continent_code' => 'AS', 'phone_code' => '992', 'currency' => 'TJS'],
            ['name' => 'Turkmenistan', 'abbreviation' => 'TM', 'zh_name' => '土库曼斯坦', 'continent_code' => 'AS', 'phone_code' => '993', 'currency' => 'TMT'],
            ['name' => 'Tunisia', 'abbreviation' => 'TN', 'zh_name' => '突尼斯', 'continent_code' => 'AF', 'phone_code' => '216', 'currency' => 'TND'],
            ['name' => 'Tonga', 'abbreviation' => 'TO', 'zh_name' => '汤加', 'continent_code' => 'OC', 'phone_code' => '676', 'currency' => 'TOP'],
            ['name' => 'Turkey', 'abbreviation' => 'TR', 'zh_name' => '土耳其', 'continent_code' => 'AS', 'phone_code' => '90', 'currency' => 'TRY'],
            ['name' => 'Trinidad and Tobago', 'abbreviation' => 'TT', 'zh_name' => '特立尼达和多巴哥', 'continent_code' => 'SA', 'phone_code' => '1809', 'currency' => 'TTD'],
            ['name' => 'Taiwan', 'abbreviation' => 'TW', 'zh_name' => '台湾省', 'continent_code' => 'AS', 'phone_code' => '886', 'currency' => 'TWD'],
            ['name' => 'Tanzania', 'abbreviation' => 'TZ', 'zh_name' => '坦桑尼亚', 'continent_code' => 'AF', 'phone_code' => '255', 'currency' => 'TZS'],
            ['name' => 'Ukraine', 'abbreviation' => 'UA', 'zh_name' => '乌克兰', 'continent_code' => 'EU', 'phone_code' => '380', 'currency' => 'UAH'],
            ['name' => 'Uganda', 'abbreviation' => 'UG', 'zh_name' => '乌干达', 'continent_code' => 'AF', 'phone_code' => '256', 'currency' => 'UGX'],
            ['name' => 'United States of America', 'abbreviation' => 'US', 'zh_name' => '美国', 'continent_code' => 'NA', 'phone_code' => '1', 'currency' => 'USD'],
            ['name' => 'Uruguay', 'abbreviation' => 'UY', 'zh_name' => '乌拉圭', 'continent_code' => 'SA', 'phone_code' => '598', 'currency' => 'UYU'],
            ['name' => 'Uzbekistan', 'abbreviation' => 'UZ', 'zh_name' => '乌兹别克斯坦', 'continent_code' => 'AS', 'phone_code' => '233', 'currency' => 'UZS'],
            ['name' => 'Saint Vincent', 'abbreviation' => 'VC', 'zh_name' => '圣文森特岛', 'continent_code' => 'NA', 'phone_code' => '1784', 'currency' => 'XCD'],
            ['name' => 'Venezuela', 'abbreviation' => 'VE', 'zh_name' => '委内瑞拉', 'continent_code' => 'SA', 'phone_code' => '58', 'currency' => 'VEF'],
            ['name' => 'Vietnam', 'abbreviation' => 'VN', 'zh_name' => '越南', 'continent_code' => 'AS', 'phone_code' => '84', 'currency' => 'VND'],
            ['name' => 'Yemen', 'abbreviation' => 'YE', 'zh_name' => '也门', 'continent_code' => 'AS', 'phone_code' => '967', 'currency' => 'YER'],
            ['name' => 'Yugoslavia', 'abbreviation' => 'YU', 'zh_name' => '南斯拉夫', 'continent_code' => 'EU', 'phone_code' => '381', 'currency' => 'YUG'],
            ['name' => 'South Africa', 'abbreviation' => 'ZA', 'zh_name' => '南非', 'continent_code' => 'AF', 'phone_code' => '27', 'currency' => 'ZAR'],
            ['name' => 'Zambia', 'abbreviation' => 'ZM', 'zh_name' => '赞比亚', 'continent_code' => 'AF', 'phone_code' => '260', 'currency' => 'ZMW'],
            ['name' => 'Zaire', 'abbreviation' => 'ZR', 'zh_name' => '扎伊尔', 'continent_code' => 'AF', 'phone_code' => '243', 'currency' => 'ZRN'],
            ['name' => 'Zimbabwe', 'abbreviation' => 'ZW', 'zh_name' => '津巴布韦', 'continent_code' => 'AF', 'phone_code' => '263', 'currency' => 'ZWL'],
        ]);
    }
}